In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# Datei einlesen
file_path = "04_61243-0002_de.csv"
df = pd.read_csv(file_path, sep=";", encoding="latin1", on_bad_lines="skip")
display(df)

                                                         Tabelle: 61243-0002
Strompreise fÃ¼r Haushalte: Deutschland, Jahre, NaN NaN                  NaN
Jahresverbrauchsklassen, Preisbestandteile      NaN NaN                  NaN
__________                                      NaN NaN                  NaN
Â© Statistisches Bundesamt (Destatis), 2026     NaN NaN                  NaN
Stand: 27.04.2026 / 13:28:22                    NaN NaN                  NaN

In [2]:
file_path = "04_61243-0002_de.csv"

df_raw = pd.read_csv(
    file_path,
    sep=";",
    encoding="utf-8-sig",
    skiprows=6,
    skipfooter=3,
    engine="python",
    header=None
)

df_raw.columns = [
    "Kategorie",
    "Energie_und_Vertrieb",
    "Kennzeichen_1",
    "Netzkosten",
    "Kennzeichen_2",
    "Steuern_Abgaben_Umlagen",
    "Kennzeichen_3"
]

# Рік
df_raw["Jahr"] = np.where(
    df_raw["Kategorie"].astype(str).str.match(r"^\d{4}$"),
    df_raw["Kategorie"],
    np.nan
)

df_raw["Jahr"] = df_raw["Jahr"].ffill()

# Залишаємо тільки реальні категорії споживання
df = df_raw[
    ~df_raw["Kategorie"].astype(str).str.match(r"^\d{4}$") &
    ~df_raw["Kategorie"].isna()
].copy()

# Прибираємо службові колонки з "e"
df = df.drop(columns=["Kennzeichen_1", "Kennzeichen_2", "Kennzeichen_3"])

# Чистимо числа
price_cols = [
    "Energie_und_Vertrieb",
    "Netzkosten",
    "Steuern_Abgaben_Umlagen"
]

for col in price_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", ".", regex=False)
    )
    df[col] = pd.to_numeric(df[col], errors="coerce")

display(df)

,Kategorie,Energie_und_Vertrieb,Netzkosten,Steuern_Abgaben_Umlagen,Jahr
3,unter 1 000 KWh,0.0925,0.1808,0.1837,2019
4,1 000 bis unter 2 500 KWh,0.0683,0.0938,0.1622,2019
5,2 500 bis unter 5 000 KWh,0.0581,0.0740,0.1556,2019
6,5 000 bis unter 15 000 KWh,0.0547,0.0592,0.1504,2019
7,15 000 KWh und mehr,0.0492,0.0444,0.1432,2019
8,Insgesamt,0.0617,0.0804,0.1571,2019
10,unter 1 000 KWh,0.1213,0.1546,0.1849,2020
11,1 000 bis unter 2 500 KWh,0.0742,0.0992,0.1659,2020
12,2 500 bis unter 5 000 KWh,0.0574,0.0864,0.1589,2020
13,5 000 bis unter 15 000 KWh,0.0577,0.0715,0.1545,2020
14,15 000 KWh und mehr,0.0502,0.0579,0.1472,2020
15,Insgesamt,0.0659,0.0894,0.1608,2020
17,unter 1 000 KWh,0.1210,0.1574,0.1891,2021
18,1 000 bis unter 2 500 KWh,0.0914,0.0937,0.1705,2021
19,2 500 bis unter 5 000 KWh,0.0803,0.0776,0.1634,2021
20,5 000 bis unter 15 000 KWh,0.0735,0.0632,0.1566,2021
21,15 000 KWh und mehr,0.0582,0.0487,0.1460,2021
22,Insgesamt,0.0824,0.0811,0.1639,2021
24,unter 1 000 KWh,0.1846,0.1663,0.1481,2022
25,1 000 bis unter 2 500 KWh,0.1435,0.0976,0.1279,2022
26,2 500 bis unter 5 000 KWh,0.1303,0.0804,0.1210,2022
27,5 000 bis unter 15 000 KWh,0.1214,0.0656,0.1146,2022
28,15 000 KWh und mehr,0.1177,0.0542,0.1091,2022
29,Insgesamt,0.1345,0.0853,0.1223,2022
31,unter 1 000 KWh,0.2516,0.1804,0.1441,2023
32,1 000 bis unter 2 500 KWh,0.2138,0.1130,0.1229,2023
33,2 500 bis unter 5 000 KWh,0.1992,0.0937,0.1145,2023
34,5 000 bis unter 15 000 KWh,0.1993,0.0742,0.1076,2023
35,15 000 KWh und mehr,0.1911,0.0559,0.0986,2023
36,Insgesamt,0.2063,0.0978,0.1161,2023
38,unter 1 000 KWh,0.2153,0.2215,0.1478,2024
39,1 000 bis unter 2 500 KWh,0.1806,0.1383,0.1241,2024
40,2 500 bis unter 5 000 KWh,0.1654,0.1147,0.1147,2024
41,5 000 bis unter 15 000 KWh,0.1640,0.0909,0.1064,2024
42,15 000 KWh und mehr,0.1554,0.0827,0.1031,2024
43,Insgesamt,0.1724,0.1217,0.1172,2024
45,unter 1 000 KWh,0.2024,0.2283,0.1596,2025
46,1 000 bis unter 2 500 KWh,0.1632,0.1393,0.1340,2025
47,2 500 bis unter 5 000 KWh,0.1481,0.1130,0.1241,2025
48,5 000 bis unter 15 000 KWh,0.1430,0.0880,0.1145,2025
49,15 000 KWh und mehr,0.1380,0.0783,0.1112,2025
50,Insgesamt,0.1546,0.1211,0.1266,2025

In [3]:
df["date_from"] = pd.to_datetime(df["Jahr"].astype(str) + "-01-01")

In [4]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [5]:
df["kategorie"] = df["kategorie"].str.replace(" ", "")

In [6]:
df["total_price_eur_per_kwh"] = (
    df["energie_und_vertrieb"] +
    df["netzkosten"] +
    df["steuern_abgaben_umlagen"]
).round(4)

In [7]:
df["is_total"] = df["kategorie"].eq("Insgesamt")

In [8]:
display(df)

,kategorie,energie_und_vertrieb,netzkosten,steuern_abgaben_umlagen,jahr,date_from,total_price_eur_per_kwh,is_total
3,unter1000KWh,0.0925,0.1808,0.1837,2019,2019-01-01,0.4570,False
4,1000bisunter2500KWh,0.0683,0.0938,0.1622,2019,2019-01-01,0.3243,False
5,2500bisunter5000KWh,0.0581,0.0740,0.1556,2019,2019-01-01,0.2877,False
6,5000bisunter15000KWh,0.0547,0.0592,0.1504,2019,2019-01-01,0.2643,False
7,15000KWhundmehr,0.0492,0.0444,0.1432,2019,2019-01-01,0.2368,False
8,Insgesamt,0.0617,0.0804,0.1571,2019,2019-01-01,0.2992,True
10,unter1000KWh,0.1213,0.1546,0.1849,2020,2020-01-01,0.4608,False
11,1000bisunter2500KWh,0.0742,0.0992,0.1659,2020,2020-01-01,0.3393,False
12,2500bisunter5000KWh,0.0574,0.0864,0.1589,2020,2020-01-01,0.3027,False
13,5000bisunter15000KWh,0.0577,0.0715,0.1545,2020,2020-01-01,0.2837,False
14,15000KWhundmehr,0.0502,0.0579,0.1472,2020,2020-01-01,0.2553,False
15,Insgesamt,0.0659,0.0894,0.1608,2020,2020-01-01,0.3161,True
17,unter1000KWh,0.1210,0.1574,0.1891,2021,2021-01-01,0.4675,False
18,1000bisunter2500KWh,0.0914,0.0937,0.1705,2021,2021-01-01,0.3556,False
19,2500bisunter5000KWh,0.0803,0.0776,0.1634,2021,2021-01-01,0.3213,False
20,5000bisunter15000KWh,0.0735,0.0632,0.1566,2021,2021-01-01,0.2933,False
21,15000KWhundmehr,0.0582,0.0487,0.1460,2021,2021-01-01,0.2529,False
22,Insgesamt,0.0824,0.0811,0.1639,2021,2021-01-01,0.3274,True
24,unter1000KWh,0.1846,0.1663,0.1481,2022,2022-01-01,0.4990,False
25,1000bisunter2500KWh,0.1435,0.0976,0.1279,2022,2022-01-01,0.3690,False
26,2500bisunter5000KWh,0.1303,0.0804,0.1210,2022,2022-01-01,0.3317,False
27,5000bisunter15000KWh,0.1214,0.0656,0.1146,2022,2022-01-01,0.3016,False
28,15000KWhundmehr,0.1177,0.0542,0.1091,2022,2022-01-01,0.2810,False
29,Insgesamt,0.1345,0.0853,0.1223,2022,2022-01-01,0.3421,True
31,unter1000KWh,0.2516,0.1804,0.1441,2023,2023-01-01,0.5761,False
32,1000bisunter2500KWh,0.2138,0.1130,0.1229,2023,2023-01-01,0.4497,False
33,2500bisunter5000KWh,0.1992,0.0937,0.1145,2023,2023-01-01,0.4074,False
34,5000bisunter15000KWh,0.1993,0.0742,0.1076,2023,2023-01-01,0.3811,False
35,15000KWhundmehr,0.1911,0.0559,0.0986,2023,2023-01-01,0.3456,False
36,Insgesamt,0.2063,0.0978,0.1161,2023,2023-01-01,0.4202,True
38,unter1000KWh,0.2153,0.2215,0.1478,2024,2024-01-01,0.5846,False
39,1000bisunter2500KWh,0.1806,0.1383,0.1241,2024,2024-01-01,0.4430,False
40,2500bisunter5000KWh,0.1654,0.1147,0.1147,2024,2024-01-01,0.3948,False
41,5000bisunter15000KWh,0.1640,0.0909,0.1064,2024,2024-01-01,0.3613,False
42,15000KWhundmehr,0.1554,0.0827,0.1031,2024,2024-01-01,0.3412,False
43,Insgesamt,0.1724,0.1217,0.1172,2024,2024-01-01,0.4113,True
45,unter1000KWh,0.2024,0.2283,0.1596,2025,2025-01-01,0.5903,False
46,1000bisunter2500KWh,0.1632,0.1393,0.1340,2025,2025-01-01,0.4365,False
47,2500bisunter5000KWh,0.1481,0.1130,0.1241,2025,2025-01-01,0.3852,False
48,5000bisunter15000KWh,0.1430,0.0880,0.1145,2025,2025-01-01,0.3455,False
49,15000KWhundmehr,0.1380,0.0783,0.1112,2025,2025-01-01,0.3275,False
50,Insgesamt,0.1546,0.1211,0.1266,2025,2025-01-01,0.4023,True

In [9]:
df = df.rename(columns={
    "kategorie": "verbrauchskategorie",
    "energie_und_vertrieb": "energie_und_vertrieb_eur_kwh",
    "netzkosten": "netzkosten_eur_kwh",
    "steuern_abgaben_umlagen": "steuern_abgaben_umlagen_eur_kwh",
    "jahr": "jahr",
    "date_from": "datum_von",
    "total_price_eur_per_kwh": "strompreis_gesamt_eur_kwh",
    "is_total": "ist_gesamt"
})

In [10]:
df["verbrauchskategorie"] = df["verbrauchskategorie"].replace({
    "unter1000KWh": "Unter 1000 kWh",
    "1000bisunter2500KWh": "1000 bis unter 2500 kWh",
    "2500bisunter5000KWh": "2500 bis unter 5000 kWh",
    "5000bisunter15000KWh": "5000 bis unter 15000 kWh",
    "15000KWhundmehr": "15000 kWh und mehr",
    "Insgesamt": "Insgesamt"
})

In [11]:
df = df[
    [
        "datum_von",
        "jahr",
        "verbrauchskategorie",
        "energie_und_vertrieb_eur_kwh",
        "netzkosten_eur_kwh",
        "steuern_abgaben_umlagen_eur_kwh",
        "strompreis_gesamt_eur_kwh",
        "ist_gesamt"
    ]
]

In [12]:
display(df)

,datum_von,jahr,verbrauchskategorie,energie_und_vertrieb_eur_kwh,netzkosten_eur_kwh,steuern_abgaben_umlagen_eur_kwh,strompreis_gesamt_eur_kwh,ist_gesamt
3,2019-01-01,2019,Unter 1000 kWh,0.0925,0.1808,0.1837,0.4570,False
4,2019-01-01,2019,1000 bis unter 2500 kWh,0.0683,0.0938,0.1622,0.3243,False
5,2019-01-01,2019,2500 bis unter 5000 kWh,0.0581,0.0740,0.1556,0.2877,False
6,2019-01-01,2019,5000 bis unter 15000 kWh,0.0547,0.0592,0.1504,0.2643,False
7,2019-01-01,2019,15000 kWh und mehr,0.0492,0.0444,0.1432,0.2368,False
8,2019-01-01,2019,Insgesamt,0.0617,0.0804,0.1571,0.2992,True
10,2020-01-01,2020,Unter 1000 kWh,0.1213,0.1546,0.1849,0.4608,False
11,2020-01-01,2020,1000 bis unter 2500 kWh,0.0742,0.0992,0.1659,0.3393,False
12,2020-01-01,2020,2500 bis unter 5000 kWh,0.0574,0.0864,0.1589,0.3027,False
13,2020-01-01,2020,5000 bis unter 15000 kWh,0.0577,0.0715,0.1545,0.2837,False
14,2020-01-01,2020,15000 kWh und mehr,0.0502,0.0579,0.1472,0.2553,False
15,2020-01-01,2020,Insgesamt,0.0659,0.0894,0.1608,0.3161,True
17,2021-01-01,2021,Unter 1000 kWh,0.1210,0.1574,0.1891,0.4675,False
18,2021-01-01,2021,1000 bis unter 2500 kWh,0.0914,0.0937,0.1705,0.3556,False
19,2021-01-01,2021,2500 bis unter 5000 kWh,0.0803,0.0776,0.1634,0.3213,False
20,2021-01-01,2021,5000 bis unter 15000 kWh,0.0735,0.0632,0.1566,0.2933,False
21,2021-01-01,2021,15000 kWh und mehr,0.0582,0.0487,0.1460,0.2529,False
22,2021-01-01,2021,Insgesamt,0.0824,0.0811,0.1639,0.3274,True
24,2022-01-01,2022,Unter 1000 kWh,0.1846,0.1663,0.1481,0.4990,False
25,2022-01-01,2022,1000 bis unter 2500 kWh,0.1435,0.0976,0.1279,0.3690,False
26,2022-01-01,2022,2500 bis unter 5000 kWh,0.1303,0.0804,0.1210,0.3317,False
27,2022-01-01,2022,5000 bis unter 15000 kWh,0.1214,0.0656,0.1146,0.3016,False
28,2022-01-01,2022,15000 kWh und mehr,0.1177,0.0542,0.1091,0.2810,False
29,2022-01-01,2022,Insgesamt,0.1345,0.0853,0.1223,0.3421,True
31,2023-01-01,2023,Unter 1000 kWh,0.2516,0.1804,0.1441,0.5761,False
32,2023-01-01,2023,1000 bis unter 2500 kWh,0.2138,0.1130,0.1229,0.4497,False
33,2023-01-01,2023,2500 bis unter 5000 kWh,0.1992,0.0937,0.1145,0.4074,False
34,2023-01-01,2023,5000 bis unter 15000 kWh,0.1993,0.0742,0.1076,0.3811,False
35,2023-01-01,2023,15000 kWh und mehr,0.1911,0.0559,0.0986,0.3456,False
36,2023-01-01,2023,Insgesamt,0.2063,0.0978,0.1161,0.4202,True
38,2024-01-01,2024,Unter 1000 kWh,0.2153,0.2215,0.1478,0.5846,False
39,2024-01-01,2024,1000 bis unter 2500 kWh,0.1806,0.1383,0.1241,0.4430,False
40,2024-01-01,2024,2500 bis unter 5000 kWh,0.1654,0.1147,0.1147,0.3948,False
41,2024-01-01,2024,5000 bis unter 15000 kWh,0.1640,0.0909,0.1064,0.3613,False
42,2024-01-01,2024,15000 kWh und mehr,0.1554,0.0827,0.1031,0.3412,False
43,2024-01-01,2024,Insgesamt,0.1724,0.1217,0.1172,0.4113,True
45,2025-01-01,2025,Unter 1000 kWh,0.2024,0.2283,0.1596,0.5903,False
46,2025-01-01,2025,1000 bis unter 2500 kWh,0.1632,0.1393,0.1340,0.4365,False
47,2025-01-01,2025,2500 bis unter 5000 kWh,0.1481,0.1130,0.1241,0.3852,False
48,2025-01-01,2025,5000 bis unter 15000 kWh,0.1430,0.0880,0.1145,0.3455,False
49,2025-01-01,2025,15000 kWh und mehr,0.1380,0.0783,0.1112,0.3275,False
50,2025-01-01,2025,Insgesamt,0.1546,0.1211,0.1266,0.4023,True

In [13]:
df.to_csv(
    "04_bereinigte_strompreisbestandteile_LV.csv",
    index=False,
    encoding="utf-8-sig"
)